steps:
  # Build container image (no cache to ensure fresh build)
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - -t
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}
      - .

  # Push image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}
      - --region=${_DEPLOY_REGION}
      - --platform=${_PLATFORM}
      - --set-env-vars=SENDGRID_API_KEY=${_SENDGRID_API_KEY}
      - --quiet

images:
  - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}

substitutions:
  _AR_HOSTNAME: us-west1-docker.pkg.dev
  _AR_PROJECT_ID: gen-lang-client-0873605374
  _AR_REPOSITORY: cloud-run-source-deploy
  _SERVICE_NAME: willem-himpe-personal-brand
  _DEPLOY_REGION: us-west1
  _PLATFORM: managed

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

